site_name: 酒井科协暑培 2024
repo_url: https://github.com/sast-summer-training-2024/sast-summer-training-2024.github.io
repo_name: SAST Summer Training 2024

theme:
  name: material
  language: zh
  custom_dir: theme/
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - content.code.annotate
    - navigation.top
    - navigation.tabs
    - navigation.indexes
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://cdn.jsdelivr.net/npm/mermaid@10.1.0/dist/mermaid.min.js'
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true

validation:
  absolute_links: ignore
  unrecognized_links: ignore

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format

# Contents
nav:
  - 首页:
    - index.md
    - 资源链接: links.md
    - 基础 Track: basic/index_basic.md
    - 前端 Track: frontend/index_frontend.md
    - 后端 Track: backend/index_backend.md
    - 游戏 Track: unity/index_unity.md
    - AI Track: ai/index_ai.md
  - 基础:
    - basic/index_basic.md
    - Linux & Git:
      - 课前准备: basic/linux_git/Pre-requisite.md
      - Linux: basic/linux_git/Linux.md
      - Git: basic/linux_git/Git.md
      - 课程回放: https://www.bilibili.com/video/BV1bM4m127DE/?share_source=copy_web&vd_source=49053b7356a25d7661b5d45f37afd1fb
    - Python:
      - 课前准备: basic/python/Pre-requisite.md
      - 讲义: basic/python/handout.md
      - 课程回放: https://www.bilibili.com/video/BV1Ny411B7Ex/?share_source=copy_web&vd_source=a80492aa87f464b5346dca18c3a9e9b3
    - Web基础:
      - 课件: basic/Web_basics/Web_basics.pdf
      - 课程回放: https://www.bilibili.com/video/BV1pb421J7cR/?share_source=copy_web&vd_source=a80492aa87f464b5346dca18c3a9e9b3
      - 作业: basic/Web_basics/hw.pdf
    - 数据库 & SQL:
      - 课前准备: basic/sql/Pre-requisite.md
      - 讲义: basic/sql/handout.md
      - 课程回放: https://www.bilibili.com/video/BV1PS42197ve/?share_source=copy_web&vd_source=a80492aa87f464b5346dca18c3a9e9b3
  - 前端:
    - frontend/index_frontend.md
    - JSTS:
      - 课前准备: frontend/JSTS/Pre-requisite.md
      - 讲义: frontend/JSTS/handout.md
      - 课程回放: frontend/JSTS/playback.md
      - 作业: https://github.com/sast-summer-training-2024/sast2024-jsts
    - React:
      - 课前准备: frontend/react/Pre-requisite.md
      - 讲义: frontend/react/handout.md
      - 课程回放: https://www.bilibili.com/video/BV1Kx4y147mZ/?share_source=copy_web&vd_source=5f41358f46c6dc60e03c3ff6ca5a8520
    - Java:
      - 课前准备: frontend/java/prerequisites.md
      - 讲义: frontend/java/handout.md
      - 课后作业: frontend/java/homework.md
      - 课程回放: https://www.bilibili.com/video/BV1Vx4y1s7br/?share_source=copy_web&vd_source=5f41358f46c6dc60e03c3ff6ca5a8520
    - Android:
      - 课前准备: frontend/android/prerequisites.md
      - 讲义: frontend/android/handout.md
      - 课后作业: frontend/android/homework.md
      - 课程回放: https://www.bilibili.com/video/BV1vdvhebEBz/?share_source=copy_web&vd_source=5f41358f46c6dc60e03c3ff6ca5a8520
  - 后端:
    - backend/index_backend.md
    - 爬虫入门:
      - 讲义: backend/crawler/slide.pdf
      - 代码: https://github.com/UbeCc/sast-2024-crawler
      - 课程回放: https://www.bilibili.com/video/BV1cb421J7u9/?share_source=copy_web&vd_source=a80492aa87f464b5346dca18c3a9e9b3
    - Django:
      - 课前准备: backend/django/prerequisites.md
      - 后端架构: backend/django/backend.md
      - Django: backend/django/django.md
      - 作业 (也是课件): https://github.com/sast-summer-training-2024/sast2024-django-hw
      - 课程回放: https://www.bilibili.com/video/BV1em42137P7/?share_source=copy_web&vd_source=5f41358f46c6dc60e03c3ff6ca5a8520
    - docker:
      - 课前准备: backend/docker/prerequisites.md
      - 讲义: backend/docker/handout.md
      - 课程回放: https://www.bilibili.com/video/BV1qS411w7Dt/?share_source=copy_web&vd_source=5f41358f46c6dc60e03c3ff6ca5a8520
    - Rust:
      - 课前准备: backend/rust/Pre-requisite.md
      - 讲义: backend/rust/handout.md
      - 课程回放: backend/rust/playback.md
  - 游戏:
    - unity/index_unity.md
    - Unity 入门:
      - 课前准备: unity/unity_basic/Pre-requisite.md
      - 讲义: unity/unity_basic/Unity_basic.pptx
      - 课程回放: https://www.bilibili.com/video/BV1GjvQe2ER3/?share_source=copy_web&vd_source=5f41358f46c6dc60e03c3ff6ca5a8520
    - Unity脚本基础与场景: unity/unity2.pdf
    - 动画基础与VFX素材应用: 
      - 课前准备: unity/unity3/Pre-requisite.md
      - 讲义: unity/unity3/unity3.pptx
  - AI:
    - ai/index_ai.md
    - 神经网络: 
      - 讲义: ai/neural-network/network.md
      - 课程回放: https://www.bilibili.com/video/BV11SvDeNEbY/?share_source=copy_web&vd_source=5f41358f46c6dc60e03c3ff6ca5a8520
    - 机器学习中的优化方法: 
      - 课前准备: ai/sast2024-optimization/intro.md
      - 讲义: https://github.com/sast-summer-training-2024/sast2024-optimization/blob/db76dd97daed72c1dc69d1ce236ae0631ea59e01/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E4%B8%AD%E7%9A%84%E4%BC%98%E5%8C%96%E6%96%B9%E6%B3%95_slides.pdf
      - 作业: https://github.com/sast-summer-training-2024/sast2024-optimization/blob/db76dd97daed72c1dc69d1ce236ae0631ea59e01/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E4%B8%AD%E7%9A%84%E4%BC%98%E5%8C%96%E6%96%B9%E6%B3%95_%E4%BD%9C%E4%B8%9A.pdf
    - 数据处理可视化与pytorch: ai/dp-and-pytorch/readme.md

