site_name: 酒井科协暑培 2024
repo_url: https://github.com/sast-summer-training-2024/sast-summer-training-2024.github.io
repo_name: SAST Summer Training 2024

theme:
  name: material
  language: zh
  custom_dir: theme/
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - content.code.annotate
    - navigation.top
    - navigation.tabs
    - navigation.indexes
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://cdn.jsdelivr.net/npm/mermaid@10.1.0/dist/mermaid.min.js'
plugins:
  - search
  - mermaid2
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true

validation:
  absolute_links: ignore
  unrecognized_links: ignore

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format

# Contents
nav:
  - 首页:
    - index.md
    - 资源链接: links.md
    - 基础 Track: basic/index_basic.md
    - 前端 Track: frontend/index_frontend.md
    - 后端 Track: backend/index_backend.md
  - 基础:
    - basic/index_basic.md
    - Linux & Git:
      - 课前准备: basic/linux_git/Pre-requisite.md
      - Linux: basic/linux_git/Linux.md
      - Git: basic/linux_git/Git.md
      - 课程回放: https://www.bilibili.com/video/BV1bM4m127DE/?share_source=copy_web&vd_source=49053b7356a25d7661b5d45f37afd1fb
    - Python:
      - 课前准备: basic/python/Pre-requisite.md
      - 讲义: basic/python/handout.md
      - 课程回放: https://www.bilibili.com/video/BV1Ny411B7Ex/?share_source=copy_web&vd_source=a80492aa87f464b5346dca18c3a9e9b3
    - Web基础:
      - 课件: basic/Web_basics/Web_basics.pdf
      - 课程回放: https://www.bilibili.com/video/BV1pb421J7cR/?share_source=copy_web&vd_source=a80492aa87f464b5346dca18c3a9e9b3
      - 作业: basic/Web_basics/hw.pdf
    - 数据库 & SQL:
      - 课前准备: basic/sql/Pre-requisite.md
      - 讲义: basic/sql/handout.md
      - 课程回放: https://www.bilibili.com/video/BV1PS42197ve/?share_source=copy_web&vd_source=a80492aa87f464b5346dca18c3a9e9b3
  - 前端:
    - frontend/index_frontend.md
    - JSTS:
      - 课前准备: frontend/JSTS/Pre-requisite.md
      - 讲义: frontend/JSTS/handout.md
      - 课程回放: https://www.bilibili.com/video/BV1R4421U7Sn/?share_source=copy_web&vd_source=a80492aa87f464b5346dca18c3a9e9b3
    - React:
      - 课前准备: frontend/react/Pre-requisite.md
      - 讲义: frontend/react/handout.md
    - Java:
      - 课前准备: frontend/java/prerequisites.md
      - 讲义: frontend/java/handout.md
      - 课后作业: frontend/java/homework.md
  - 后端:
    - backend/index_backend.md
    - 爬虫入门:
      - 讲义: backend/crawler/slide.pdf
      - 代码: https://github.com/UbeCc/sast-2024-crawler
      - 课程回放: https://www.bilibili.com/video/BV1cb421J7u9/?share_source=copy_web&vd_source=a80492aa87f464b5346dca18c3a9e9b3
    - Django:
      - 课前准备: backend/django/prerequisites.md
      - 后端架构: backend/django/backend.md
      - Django: backend/django/django.md
      - 作业 (也是课件): https://github.com/sast-summer-training-2024/sast2024-django-hw
  - AI:
    - ai/index_ai.md
    - 神经网络: ai/neural-network/network.md
    - 数据处理可视化与pytorch: ai/dp-and-pytorch/readme.md